{
 "title": "CloudBees CI - Build Performance",
 "tags": [
  "builds",
  "ci",
  "agents",
  "cloudbees"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(up{container=\"jenkins\", namespace=\"$namespace\"},service)"
    }
   },
   { "name": "namespace", "query": "cbci" },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values({container=\"jenkins\", service=\"$service\", namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: space-between; align-items: flex-start; background: linear-gradient(90deg, #232526 0%, #414345 100%); padding: 18px 28px; border-radius: 16px; border: 1.5px solid #35373a; box-shadow: 0 4px 24px rgba(0,0,0,0.13); width: 100%; height: 100%;\">\n  <!-- Left: Logo and Titles -->\n  <div style=\"display: flex; align-items: center;\">\n    <img\n      src=\"https://www.jenkins.io/images/logos/automotive/automotive.png\"\n      alt=\"Jenkins Automotive\"\n      width=\"110\"\n      height=\"110\"\n      style=\"margin-right: 32px; border-radius: 12px; box-shadow: 0 2px 16px rgba(0,0,0,0.13); background: #fff; padding: 10px;\"\n    >\n    <div>\n      <h1 style=\"color: #fff; margin: 0; font-size: 2.3rem; font-weight: 800; letter-spacing: 1.2px; white-space: nowrap;\">\n        Build Performance\n      </h1>\n      <h3 style=\"margin: 10px 0 0 0; font-size: 1.22rem; font-weight: 700; letter-spacing: 0.2px; white-space: nowrap;\">\n        <a href=\"https://docs.cloudbees.com/docs/cloudbees-ci/latest/\" target=\"_blank\" style=\"color: #2196f3; text-decoration: underline; font-weight: 700;\">CloudBees CI on Modern</a>\n      </h3>\n      <h3 style=\"margin: 10px 0 0 0; font-size: 1.22rem; font-weight: 700; letter-spacing: 0.2px; white-space: nowrap;\">\n        Enterprise Jenkins running on Kubernetes\n      </h3>\n    </div>\n  </div>\n  <!-- Right: Notes Section -->\n  <div style=\"display: flex; flex-direction: column; justify-content: center; min-width: 420px; max-width: 600px; background: rgba(30,32,34,0.92); border-radius: 10px; padding: 22px 36px; box-shadow: 0 2px 8px rgba(0,0,0,0.10);\">\n    <div style=\"border-bottom: 1px solid #444; margin-bottom: 12px; padding-bottom: 7px;\">\n      <h2 style=\"color: #fff; font-size: 1.12rem; font-weight: 700; margin: 0; letter-spacing: 0.6px;\">Notes</h2>\n    </div>\n    <ul style=\"color: #e0e0e0; font-size: 1.08rem; margin: 0; padding-left: 18px; line-height: 2; list-style-position: inside;\">\n      <li style=\"white-space: nowrap;\">Datasources: Prometheus, Tempo</li>\n      <li style=\"white-space: nowrap;\">Metrics: <b><a href=\"https://plugins.jenkins.io/metrics/\" target=\"_blank\" style=\"color: #2196f3; text-decoration: underline; font-weight: 700;\">Jenkins Metrics plugin</a></b> formatted by <a href=\"https://docs.cloudbees.com/docs/release-notes/latest/plugins/cloudbees-prometheus-plugin/\" target=\"_blank\" style=\"color: #2196f3; text-decoration: underline; font-weight: 700;\">CloudBees Prometheus Plugin</a>, <a href=\"https://plugins.jenkins.io/opentelemetry/\" target=\"_blank\" style=\"color: #2196f3; text-decoration: underline; font-weight: 700;\">OpenTelemetry plugin</a>\n      <li style=\"white-space: nowrap;\">The Dashboard is compatible with <a href=\"https://docs.cloudbees.com/docs/cloudbees-ci/latest/ha/ha-considerations#_ha_and_rest_api_endpoints\" target=\"_blank\" style=\"color: #2196f3; text-decoration: underline; font-weight: 700;\">CloudBees CI HA/HS</a></li>\n    </ul>\n  </div>\n</div>\n"
   }
  },
  {
   "title": "Jenkins | Overview of Current Status (by Service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Build Completion Status",
   "type": "piechart",
   "description": "Comparison of build completion status' within specified time interval.\n\nSuccess: The Build has no errors, and completed.\n\nFailure: The Build had a fatal error, and did not complete.\n\nAborted: The Build was interrupted before it reaches its expected end. For example, the user has stopped it manually or there was a time-out.\n\nUnstable: The Build had some errors but they were not fatal. The build completed.\n\nNot Built: The Build was scheduled but cancelled and not started. This could be due to manual intervention or concurrent builds are not allowed.",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (increase(jenkins_runs_unstable_total{service=\"$service\"}[$__range]))",
     "legendFormat": "Unstable"
    },
    {
     "expr": "sum (increase(jenkins_runs_aborted_total{service=\"$service\"}[$__range]))",
     "legendFormat": "Aborted"
    },
    {
     "expr": "sum (increase(jenkins_runs_success_total{service=\"$service\"}[$__range]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum (increase(jenkins_runs_failure_total{service=\"$service\"}[$__range]))",
     "legendFormat": "Failure"
    },
    {
     "expr": "sum (increase(jenkins_runs_not_built_total{service=\"$service\"}[$__range]))",
     "legendFormat": "Not Built"
    }
   ]
  },
  {
   "title": "Average Build Time",
   "type": "bargauge",
   "description": "Average time spent in the building.\n\nBuild: Total time spent executing the build.\n\nTotal: Time spent in the queue as well as completing the build.",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jenkins_job_total_duration{service=\"$service\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "avg(jenkins_job_building_duration{service=\"$service\"})",
     "legendFormat": "Building"
    }
   ]
  },
  {
   "title": "Average Queue Time",
   "type": "bargauge",
   "description": "Average time spent in the queue.\n\nQueuing: Total time spent in the queue before build starting.\n\nWaiting: Time spent in the quiet period.\n\nBlocked: Cause could be target label is busy, target node is offline, target node is busy, target label is offline.\n",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jenkins_job_queuing_duration{service=\"$service\"})",
     "legendFormat": "Queuing"
    },
    {
     "expr": "avg(jenkins_job_waiting_duration{service=\"$service\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "avg(jenkins_job_blocked_duration{service=\"$service\"})",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Build Rate (per 1h)",
   "type": "stat",
   "description": "Number of Builds per hour",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(jenkins_runs_total_total{service=\"$service\"}[$__range])) * 3600",
     "legendFormat": "{{controller_name}}"
    }
   ]
  },
  {
   "title": "Total Number of Builds",
   "type": "stat",
   "description": "Number of builds during the time period.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg (increase(jenkins_runs_total_total{service=\"$service\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of Jobs",
   "type": "stat",
   "description": "Total number of jobs",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jenkins_job_count_value{service=\"$service\"})",
     "legendFormat": "ALL"
    }
   ]
  },
  {
   "title": "Jenkins | Build Trends (by Service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "Build Status",
   "type": "timeseries",
   "description": "Prometheus Build Performance data resets all metrics back to 0 when a controller restarts.",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "avg(jenkins_runs_success_total{service=\"$service\"})",
     "legendFormat": "Success"
    },
    {
     "expr": "avg(jenkins_runs_failure_total{service=\"$service\"})",
     "legendFormat": "Failure"
    },
    {
     "expr": "avg(jenkins_runs_unstable_total{service=\"$service\"})",
     "legendFormat": "Unstable"
    },
    {
     "expr": "sum(jenkins_runs_aborted_total{service=\"$service\"})",
     "legendFormat": "Aborted"
    },
    {
     "expr": "sum(jenkins_runs_not_built_total{service=\"$service\"})",
     "legendFormat": "Not Built"
    }
   ]
  },
  {
   "title": "Average Build Time",
   "type": "timeseries",
   "description": "Average time spent in the building.\n\nBuild: Total time spent executing the build.\n\nTotal: Time spent in the queue as well as completing the build.",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(jenkins_job_total_duration{service=\"$service\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "avg(jenkins_job_building_duration{service=\"$service\"})",
     "legendFormat": "Building"
    }
   ]
  },
  {
   "title": "Build Rate (per 1h)",
   "type": "timeseries",
   "description": "Number of Builds per hour",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(rate(jenkins_runs_total_total{service=\"$service\"}[$__range])) * 3600",
     "legendFormat": "{{controller_name}}"
    }
   ]
  },
  {
   "title": "Average Queue Time",
   "type": "timeseries",
   "description": "Average time spent in the queue.\n\nQueuing: Total time spent in the queue before build starting.\n\nWaiting: Time spent in the quiet period.\n\nBlocked: Cause could be target label is busy, target node is offline, target node is busy, target label is offline.\n",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(jenkins_job_queuing_duration{service=\"$service\"})",
     "legendFormat": "Queuing"
    },
    {
     "expr": "avg(jenkins_job_waiting_duration{service=\"$service\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "avg(jenkins_job_blocked_duration{service=\"$service\"})",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Opentelemetry | Tracing (By Service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 }
  },
  {
   "title": "Top Slowest Builds (>1s)*",
   "type": "table",
   "description": "Filtered table of the slowest builds that have a longer duration than 1 second. Sorted by longest at the top.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "filters": [
      { "id": "a4c2a25f", "operator": "=", "scope": "resource" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=~",
       "scope": "span",
       "tag": "name",
       "value": [ ".*BUILD.*" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "query": "{resource.tenant = \"$service\" && name=~\".*BUILD.*\" && duration > 1s}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Top Executed Pipelines (> 1 record) *",
   "type": "table",
   "description": "Filtered table of the number of executed builds that have more than 1 records. Sorted by more recurrent at the top.",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 63 },
   "targets": [
    {
     "limit": 20,
     "query": "{resource.tenant = \"$service\" && name=~\".*BUILD.*\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Top Slowest Stages (>1s)*",
   "type": "table",
   "description": "Filtered table of the slowest stages that have a longer duration than 1 second. Sorted by longest at the top.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "filters": [
      { "id": "a4c2a25f", "operator": "=", "scope": "resource" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=~",
       "scope": "span",
       "tag": "name",
       "value": [ ".*BUILD.*" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "query": "{status=ok && name=~\".*Stage:.*\" && resource.tenant = \"$service\" && duration > 1s}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Job types",
   "type": "table",
   "description": "Filtered table of the type of jobs",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 71 },
   "targets": [
    {
     "filters": [
      { "id": "a4c2a25f", "operator": "=", "scope": "resource" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=~",
       "scope": "span",
       "tag": "name",
       "value": [ ".*BUILD.*" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "query": "{span.ci.pipeline.type=~\".*\" && resource.tenant = \"$service\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Top Error Causes (> 1 record)",
   "type": "table",
   "description": "Filtered table of the type of errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "filters": [
      { "id": "a4c2a25f", "operator": "=", "scope": "resource" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=~",
       "scope": "span",
       "tag": "name",
       "value": [ ".*BUILD.*" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "query": "{span.jenkins.pipeline.step.interruption.causes=~\".*\" && resource.tenant = \"$service\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Opentelemetry | Agents (By Pods)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 }
  },
  {
   "title": "Agents",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "sum(jenkins_agents_total{k8s_pod_name=\"$pod\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(jenkins_agents_online{k8s_pod_name=\"$pod\"})",
     "legendFormat": "Online"
    },
    {
     "expr": "sum(jenkins_agents_offline{k8s_pod_name=\"$pod\"})",
     "legendFormat": "Offline"
    }
   ]
  }
 ]
}