{
 "title": "CloudBees CI - Infra and Service Check",
 "description": "Dashboard for monitoring CloudBees CI infrastructure and service health. Provides visibility into Kubernetes resources, JVM metrics, HTTP requests, and system events.",
 "tags": [
  "cloudbees",
  "jenkins",
  "monitoring",
  "kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "cbci" },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_pod_info{pod=\"$pod\"}, node)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(up{container=\"jenkins\", namespace=\"$namespace\"},service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(up{container=\"jenkins\", service=\"$service\", namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: space-between; align-items: flex-start; background: linear-gradient(90deg, #232526 0%, #414345 100%); padding: 18px 28px; border-radius: 16px; border: 1.5px solid #35373a; box-shadow: 0 4px 24px rgba(0,0,0,0.13); width: 100%; height: 100%;\">\n  <!-- Left: Logo and Titles -->\n  <div style=\"display: flex; align-items: center;\">\n    <img\n      src=\"https://www.jenkins.io/images/logos/jenkins/jenkins.png\"\n      alt=\"Jenkins Logo\"\n      width=\"110\"\n      height=\"110\"\n      style=\"margin-right: 32px; border-radius: 12px; box-shadow: 0 2px 16px rgba(0,0,0,0.13); background: #fff; padding: 10px;\"\n    >\n    <div>\n      <h1 style=\"color: #fff; margin: 0; font-size: 2.3rem; font-weight: 800; letter-spacing: 1.2px; white-space: nowrap;\">\n        Infrastructure &amp; Service Health Checks \n      </h1>\n      <h3 style=\"margin: 10px 0 0 0; font-size: 1.22rem; font-weight: 700; letter-spacing: 0.2px; white-space: nowrap;\">\n        <a href=\"https://docs.cloudbees.com/docs/cloudbees-ci/latest/\" target=\"_blank\" style=\"color: #2196f3; text-decoration: underline; font-weight: 700;\">CloudBees CI on Modern</a>\n      </h3>\n      <h3 style=\"margin: 10px 0 0 0; font-size: 1.22rem; font-weight: 700; letter-spacing: 0.2px; white-space: nowrap;\">\n        Enterprise Jenkins running on Kubernetes\n      </h3>\n    </div>\n  </div>\n  <!-- Right: Notes Section -->\n  <div style=\"display: flex; flex-direction: column; justify-content: center; min-width: 420px; max-width: 600px; background: rgba(30,32,34,0.92); border-radius: 10px; padding: 22px 36px; box-shadow: 0 2px 8px rgba(0,0,0,0.10);\">\n    <div style=\"border-bottom: 1px solid #444; margin-bottom: 12px; padding-bottom: 7px;\">\n      <h2 style=\"color: #fff; font-size: 1.12rem; font-weight: 700; margin: 0; letter-spacing: 0.6px;\">Notes</h2>\n    </div>\n    <ul style=\"color: #e0e0e0; font-size: 1.08rem; margin: 0; padding-left: 18px; line-height: 2; list-style-position: inside;\">\n      <li style=\"white-space: nowrap;\">Datasources: Prometheus, Loki</li>\n      <li style=\"white-space: nowrap;\">Metrics: <b><a href=\"https://plugins.jenkins.io/metrics/\" target=\"_blank\" style=\"color: #2196f3; text-decoration: underline; font-weight: 700;\">Jenkins Metrics plugin</a></b> formatted by <a href=\"https://docs.cloudbees.com/docs/release-notes/latest/plugins/cloudbees-prometheus-plugin/\" target=\"_blank\" style=\"color: #2196f3; text-decoration: underline; font-weight: 700;\">CloudBees Prometheus Plugin</a>, <a href=\"https://github.com/kubernetes/kube-state-metrics\" target=\"_blank\" style=\"color: #2196f3; text-decoration: underline; font-weight: 700;\">kube-state-metrics</a>\n      <li style=\"white-space: nowrap;\">The Dashboard is compatible with <a href=\"https://docs.cloudbees.com/docs/cloudbees-ci/latest/ha/ha-considerations#_ha_and_rest_api_endpoints\" target=\"_blank\" style=\"color: #2196f3; text-decoration: underline; font-weight: 700;\">CloudBees CI HA/HS</a></li>\n    </ul>\n  </div>\n</div>\n"
   }
  },
  { "title": "K8s | Description (by Pod)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Container Image Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=~\"cbci\", image!=\"\", image!~\"pause\", pod=\"$pod\"}[$__rate_interval])) by (image)",
     "legendFormat": "{{ image }}"
    }
   ]
  },
  {
   "title": "Running on",
   "type": "stat",
   "description": "Shows the node where this pod is running. Click to view node details.",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{pod=\"$pod\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Pod IP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{pod=\"$pod\"}",
     "legendFormat": "{{ pod_ip }}"
    }
   ]
  },
  {
   "title": "Last Terminated Exit Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_exitcode{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Created by",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{pod=\"$pod\"}",
     "legendFormat": "{{ created_by_kind }}: {{ created_by_name }}"
    }
   ]
  },
  {
   "title": "Jenkins & Prometheus | Readiness (by Service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Jenkins Health Score",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(jenkins_health_check_score{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "VM Uptime Hours",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(up{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "avg(process_max_fds{service=~\"$service\"}) ",
     "legendFormat": "Max Open Files"
    },
    {
     "expr": "avg(process_open_fds{service=~\"$service\"}) ",
     "legendFormat": "Open files"
    }
   ]
  },
  { "title": "Jenkins | JVM (by Pod)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vm_memory_heap_usage {pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vm_memory_non_heap_usage{pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Heap vs Non-Heap Usage ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(vm_memory_non_heap_usage{pod=\"$pod\"})",
     "legendFormat": "Non-Heap"
    },
    {
     "expr": "avg(vm_memory_heap_usage{pod=\"$pod\"})",
     "legendFormat": "Heap"
    }
   ]
  },
  {
   "title": "Number Threads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(vm_count{pod=~\"$pod\"})",
     "legendFormat": "Number of Threads"
    }
   ]
  },
  {
   "title": "Total Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(vm_memory_total_used{pod=~\"$pod\"})",
     "legendFormat": "{{pod}} JVM Total Memory used"
    }
   ]
  },
  {
   "title": "N. of Deadlocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vm_deadlock_count{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "N. of Block Traces",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vm_blocked_count{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "GC Throughput (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - sum(increase(vm_gc_G1_Concurrent_GC_time{pod=\"$pod\"}[5m]))/(count(vm_gc_G1_Concurrent_GC_time{pod=\"$pod\"}) * 5 * 60 * 1000))",
     "legendFormat": "GC Time (ms)"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(vm_cpu_load{pod=~\"$pod\"})",
     "legendFormat": "{{pod}} JVM CPU Load"
    }
   ]
  },
  {
   "title": "GC Latency (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(vm_gc_G1_Concurrent_GC_time{pod=\"$pod\"}[5m])) / sum(increase(vm_gc_G1_Concurrent_GC_time{pod=\"$pod\"}[5m]))",
     "legendFormat": "GC Latency (%)"
    }
   ]
  },
  { "title": "K8s | File System (by Pod)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Persistent Volumes - Capacity and usage in %",
   "type": "timeseries",
   "description": "Panel only works with Block Storage types (e.g. EBS in AWS). kubelet doesn't collect detailed volume statistics for NFS mounts by default (e.g. EFS in AWS). ",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"jenkins-home-${pod}\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_capacity_bytes{ persistentvolumeclaim=\"jenkins-home-${pod}\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Capacity and usage in bytes",
   "type": "timeseries",
   "description": "Panel only works with Block Storage types (e.g. EBS in AWS). kubelet doesn't collect detailed volume statistics for NFS mounts by default (e.g. EFS in AWS). ",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"jenkins-home-${pod}\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{ persistentvolumeclaim }} - Used"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"jenkins-home-${pod}\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{ persistentvolumeclaim }} - Capacity"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Inodes",
   "type": "timeseries",
   "description": "Panel only works with Block Storage types (e.g. EBS in AWS). kubelet doesn't collect detailed volume statistics for NFS mounts by default (e.g. EFS in AWS). ",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(kubelet_volume_stats_inodes_used{persistentvolumeclaim=\"jenkins-home-${pod}\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_inodes{persistentvolumeclaim=\"jenkins-home-${pod}\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Jenkins | HTTP Request (by Pod)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true
  },
  {
   "title": "HTTP Request Duration 99%",
   "type": "timeseries",
   "description": "The 99% percentile of HTTP Requests handled by Jenkins masters.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "avg(http_requests{pod=~\"$pod\",quantile=\"0.99\"})"
    }
   ]
  },
  {
   "title": "Good HTTP Request Ratio",
   "type": "timeseries",
   "description": "The ratio of ok (200) request out of all requests.",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 55 },
   "targets": [
    {
     "expr": "avg(http_responseCodes_ok_total{pod=~\"$pod\"})/ \navg(http_requests_count{pod=~\"$pod\"}) "
    }
   ]
  },
  {
   "title": "HTTP Server Errors",
   "type": "timeseries",
   "description": "Http Server Errors (500)",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 55 },
   "targets": [
    {
     "expr": "avg(rate(http_responseCodes_serverError_total{pod=~\"$pod\"}[1m]))"
    }
   ]
  },
  { "title": "Jenkins | Plugins (by Service)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Plugins Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jenkins_plugins_failed{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Plugins Active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jenkins_plugins_active{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Plugins Update Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jenkins_plugins_withUpdate{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Plugins inactive",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jenkins_plugins_inactive{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Jenkins - Audit Trail | Auditing (by Service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 }
  },
  {
   "title": "Audit Trail - Configuration Updates",
   "type": "logs",
   "description": "Auditing updates on the configuration of the System or Jobs.",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "{com_cloudbees_cje_tenant=\"$service\"} |= `[Audit]` != `Started by`"
    }
   ]
  }
 ]
}